default: &default
  adapter: postgresql
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000
  encoding: utf8
  username:
  password:

development:
  <<: *default
  database: kntaw_digg_development

test:
  <<: *default
  database: kntaw_digg_test

production:
  <<: *default
  database: kntaw_digg_production
  username:
  password: <%= ENV['SERVER_DATABASE_PASSWORD'] %>

